language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - DJANGO='django>=1.4.2,<1.5'
  - DJANGO='django>=1.5,<1.6'
  - DJANGO='git+git://github.com/django/django.git@1.6b1'
matrix:
  exclude:
    - python: 3.2
      env: DJANGO='django>=1.4.2,<1.5'
    - python: 3.3
      env: DJANGO='django>=1.4.2,<1.5'
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install coveralls $DJANGO flake8
  - pip install -e .
before_script:
  - export DJANGO_SETTINGS_MODULE=test_settings
  - flake8 .
script:
  - coverage run --include='*qurltemplatetag*' --omit='*test_settings.py,*tests.py' $(which django-admin.py) test qurltemplatetag
after_success:
  - coveralls